server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///blog?serverTimezone=Asia/Shanghai

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: blog.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



blogserver:
  #请求图片使用 完整url地址前缀  http://localhost:8888 ！！#弃用，功能在前端完成
  serverIP: "http://localhost:8888/"
  #文件结构   项目文件夹/blogData/imgs/图片     项目文件夹/blogData/articles/文章
  dataPath: "blogData"
  imgPath: "imgs"
  articlePath: "articles"