server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///blog?serverTimezone=Asia/Shanghai


mybatis-plus:
  mapper-locations: classpath:/mapper/*mapper.xml
  type-aliases-package: blog
  configuration:
    map-underscore-to-camel-case: true